### ISSUE TITLE
Missing libmypaint-gegl dependency

### ISSUE THREAD

**Issue by SvenPuschmann** [samrocketman/vagrant-gimp#10]
First of all thanks for providing an out-of-the-box development and test environment for GIMP.
Yesterday (27.12.2015) I tested the VM, but the GIMP build stopped with the following error: 

checking for LIBMYPAINTGEGL... no
configure: error: Package requirements (libmypaint-gegl >= 1.1) were not met:

No package 'libmypaint-gegl' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBMYPAINTGEGL_CFLAGS
and LIBMYPAINTGEGL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Configure failed or did not finish!

Now that libmypaint-gegl has become a hard dependency of GIMP (see commit d01ba07ed62eeccd237ffc560573d15c27e7efb1 from 21.12.2015) it needs to be installed in the VM, too. The topic is discussed in more general at https://mail.gnome.org/archives/gimp-developer-list/2015-December/msg00034.html.
Keep up the good work with this VM :-)

Greetings, Sven

**Comment by samrocketman** [comment]
Thanks for the report.  I'll spin up the VM and try getting it back into a build-able state again.

**Comment by samrocketman** [comment]
@scit2010 I notice the latest [gimp-master builds](https://build.gimp.org/job/gimp-master/1957/console) are failing due to the missing libmypaint dependency as well.

Do you recommend I always build from the latest libmypaint `master` or build a specific version of libmypaint and stick to it?

**Comment by SvenPuschmann** [comment]
On  1.1.2016 at 9:34 PM Sam Gleske wrote:

> @scit2010 https://github.com/scit2010 I notice the latest gimp-master
> builds https://build.gimp.org/job/gimp-master/1957/console are failing
> due to the missing libmypaint dependency as well.
> 
> Do you recommend I always build from the latest libmypaint |master| or
> build a specific version of libmypaint and stick to it?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/samrocketman/vagrant-gimp/issues/10#issuecomment-168336101.

Hi Sam,

I honestly don't know how to answer this question as I haven't followed
the latest development that much.
But I guess Mitch, Jonnor or Daniel Sabo will be able to answer this.

Greetings and have a happy new year,

Sven

**Comment by samrocketman** [comment]
Happy new year, I'll ask in IRC then.
